# Generated by Django 2.2.4 on 2019-08-26 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='session',
            new_name='batch',
        ),
    ]
